config/routes.rb
NouianRails::Application.routes.draw do
  resources :roles

  match '/panel', :controller => 'profiles', :action => 'panel', :as => :panel
  resources :profiles

  devise_for :users

  resources :rates

  resources :orders

  resources :questions

  resources :categories

  resources :products

  resources :shops

  root :to => "products#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :answered_at, :content, :made_at
  belongs_to :product
  belongs_to :profile
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :made_at %><br />
    <%= f.time_select :made_at %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :answered_at %><br />
    <%= f.time_select :answered_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Made at</th>
    <th>Answer</th>
    <th>Answered at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.content %></td>
    <td><%= question.made_at %></td>
    <td><%= question.answer %></td>
    <td><%= question.answered_at %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @question.content %>
</p>

<p>
  <b>Made at:</b>
  <%= @question.made_at %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>

<p>
  <b>Answered at:</b>
  <%= @question.answered_at %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>