config/routes.rb
NouianRails::Application.routes.draw do
  resources :roles

  match '/panel', :controller => 'profiles', :action => 'panel', :as => :panel
  resources :profiles

  devise_for :users

  resources :rates

  resources :orders

  resources :questions

  resources :categories

  resources :products

  resources :shops

  root :to => "products#index"

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :comment, :completed, :reason, :value
  belongs_to :order
  belongs_to :profile
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Comment</th>
    <th>Completed</th>
    <th>Reason</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.value %></td>
    <td><%= rate.comment %></td>
    <td><%= rate.completed %></td>
    <td><%= rate.reason %></td>
    <td><%= link_to 'Show', rate %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
    <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @rate.value %>
</p>

<p>
  <b>Comment:</b>
  <%= @rate.comment %>
</p>

<p>
  <b>Completed:</b>
  <%= @rate.completed %>
</p>

<p>
  <b>Reason:</b>
  <%= @rate.reason %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>