config/routes.rb
NouianRails::Application.routes.draw do
  resources :roles

  match '/panel', :controller => 'profiles', :action => 'panel', :as => :panel
  resources :profiles

  devise_for :users

  resources :rates

  resources :orders

  resources :questions

  resources :categories

  resources :products

  resources :shops

  root :to => "products#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user

    if user.role? :administrator
      can :manage, :all
    elsif user.role? :seller
      can :manage, Products
    else 
      can :read, :all
    end
  end
end

app/models/categories_product.rb
class CategoriesProduct < ActiveRecord::Base
	attr_accessible :product_id, :category_id
	belongs_to :product
  	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :parent
  #has_many :categories_products
  #has_many :products, :through => :categories_products
  has_and_belongs_to_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :buyer_rate, :completed, :made_at, :quantity, :seller_rate, :total
  has_many :products
  #only two rates:
  has_many :rates 
  belongs_to :profile
end

app/models/product.rb
class Product < ActiveRecord::Base
  after_create :decrease_credit
  attr_accessible :color, :description, :featured, :finished, :material, 
  				  :name, :price, :quantity, :category_ids, :product_images_attributes
  #has_many :categories_products
  #has_many :categories, :through => :categories_products
  #accepts_nested_attributes_for :categories_products
  has_and_belongs_to_many :categories
  belongs_to :shop
  has_many :questions
  has_many :product_images
  belongs_to :order
  accepts_nested_attributes_for :product_images
  validates :color, :description, :finished, :material, 
  				  :name, :price, :quantity, :category_ids, :presence => true
  
  validates :name, :length => { :minimum => 3 }
  validates :quantity, :numericality => { :greater_than => 0 , :less_than => 20}
  validates :price, :numericality => { :greater_than => 0 }
  validates :description, :length => { :minimum => 20 }

  #has_many :tags

  def decrease_credit
   self.shop.ammount -= 3 # el credito a descontarse
   if self.featured != 0 && self.shop.ammount > 10
   	self.shop.ammount -= 10
   else
   	self.update_featured_false
   end
   self.shop.save
  end

  def update_featured_false
	self.update_attribute(:featured, false)  	
  end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  attr_accessible :product_id, :product_photo
  belongs_to :product
  has_attached_file :product_photo, 
  			:styles => { :medium => "300x300>", :thumb => "100x100>" },
  			#:url  => "/assets/shops/:id/:style/:basename.:extension",
  			#:path => ":rails_root/public/assets/shops/:id/:style/:basename.:extension"
  			:storage => :s3,     		
     		:s3_credentials => "#{Rails.root}/config/s3.yml",
     		:path => "/products/:photo_product_id/:style/:basename.:extension"
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  before_create :default_values
  attr_accessible :address, :city, :country, :first_name, :last_name, :postal_code, :state, :telephone
  #,:negative_as_buyer, :negative_as_seller, :overall_buyer, :overall_seller, 
  #:positive_as_buyer, :positive_as_seller,  
  #:total_boughts, :total_sales
  belongs_to :user
  has_one :shop 
  has_many :questions
  has_many :orders
  has_many :rates
  validates :address, :city, :country, :first_name, :last_name, :telephone, :state, :presence => true
  validates :first_name, :last_name, :length => { :minimum => 2 }
  validates :postal_code, :telephone, :numericality => true


  def default_values
    self.negative_as_buyer  ||= 0
    self.negative_as_seller ||= 0
    self.positive_as_buyer  ||=  0
    self.positive_as_seller ||=  0
    self.overall_buyer      ||=  100
    self.overall_seller     ||=  100
    self.total_sales        ||=  0
    self.total_boughts      ||=  0    
  end



end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :answered_at, :content, :made_at
  belongs_to :product
  belongs_to :profile
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :comment, :completed, :reason, :value
  belongs_to :order
  belongs_to :profile
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :city, :country, :description, :name, :state, :image_shop
  before_create :default_values
  has_many :products
  belongs_to :profile
  has_attached_file :image_shop, :styles => { :medium => "300x300>", :thumb => "100x100>" },
  			#:url  => "/assets/shops/:id/:style/:basename.:extension",
  			#:path => ":rails_root/public/assets/shops/:id/:style/:basename.:extension"
  			:storage => :s3,     		
     		:s3_credentials => "#{Rails.root}/config/s3.yml",
     		:path => "/shops/:id/:style/:basename.:extension"


  validates :city, :country, :description, :name, :state, :presence => true
  validates :name, :length => { :minimum => 3 }
  validates :description, :length => { :minimum => 20 }
  
  def default_values
  	self.ammount = 50.0 #define la cantidad inicial de credito.
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # attr_accessible :title, :body
  has_one :profile

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NouianRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Nouian</a>
        <div class="nav-collapse">
          <ul class="nav">            
            <li><%= link_to "Exploarar Productos", products_path %></li>
            <li><%= link_to "Explorar Tiendas", shops_path %></li>
            <% if user_signed_in? && !current_user.profile.nil? %>
              <% if current_user.profile.shop.nil? %>
                <li><%= link_to "Vende", new_shop_path %></li>            
             <% else %>
               <li><%= link_to "Vende", new_product_path %></li>            
             <% end %>
            <%end %>
             <li><%= link_to "Contactanos" %></li>
          

            <ul class="nav pull-right">
                  <li id="fat-menu" class="dropdown">
                    <% if user_signed_in? %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email%>
                      <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%=link_to "Panel", panel_url %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                    <% else %>
                     <%= link_to "sign in", new_user_session_path  %>
                    <% end %>
                  </li>
                </ul>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
<%- flash.each do |k, v| %>
    <div id="<%= k %>"><%= v %></div>
<% end %> 

<%= yield %>


</body>
</html>

app/views/layouts/back-end.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NouianRails Backend!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Nouian</a>
        <div class="nav-collapse">
          <ul class="nav">            
            <li><%= link_to "Exploarar Productos", products_path %></li>
            <li><%= link_to "Explorar Tiendas", shops_path %></li>
            <% if user_signed_in? %>
              <% if current_user.profile.shop.nil? %>
                <li><%= link_to "Vende", new_shop_path %></li>            
             <% else %>
               <li><%= link_to "Vende", new_product_path %></li>            
             <% end %>
            <%end %>
             <li><%= link_to "Contactanos" %></li>
          

            <ul class="nav pull-right">
                  <li id="fat-menu" class="dropdown">
                    <% if user_signed_in? %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email%>
                      <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%=link_to "Panel", panel_url %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                    <% else %>
                     <%= link_to "sign in", new_user_session_path  %>
                    <% end %>
                  </li>
                </ul>
            
          </ul>
        </div>
      </div>
    </div>
  </div>

    <div role="main">
     <div id="content">
        <div id="contenido">  
          <div id="containers">
            <% flash.each do |k, v| %>
              <div id="<%= k %>"><%= v %></div>
            <% end %> 
            <%= yield %>
          </div><!--Termina container=-->  
        </div> <!--Termina contenido=-->  
    </div><!--end content=-->
  <div class="clear"></div>
  <div id="footer">
          <div id="menufooter">
          <ul>
            <li><a href="javascript:void(0)">Acerca</a></li>
            <li><a href="javascript:void(0)">Blog</a></li>
            <li><a href="javascript:void(0)">Ayuda</a></li>
            <li><a href="javascript:void(0)">Terminos</a></li>
          </ul>
          </div>
          <span>Nouian © 2012</span>
  </div> <!--end footer=--> 
</body>
</html>